name: ML Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/

    - name: Train model and save artifact
      run: |
        python src/train.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model.pkl
